module WebAudio

  require 'native_helpers'
  require 'interfaces/audio_param'
  require 'interfaces/audio_node'
  require 'interfaces/analyser_node'
  require 'interfaces/audio_buffer'
  require 'interfaces/audio_buffer_source_node'
  autoload :AudioContext,                    'interfaces/audio_context'
  autoload :MediaElementAudioSourceNode,     'interfaces/media_element_audio_source_node'
  autoload :MediaStreamAudioSourceNode,      'interfaces/media_stream_audio_source_node'
  autoload :MediaStreamAudioDestinationNode, 'interfaces/media_stream_audio_destination_node'
  autoload :ScriptProcessorNode,             'interfaces/script_processor_node'
  autoload :StereoPannerNode,                'interfaces/stereo_panner_node'
  autoload :AnalyserNode,                    'interfaces/analyser_node'
  autoload :BiquadFilterNode,                'interfaces/biquad_filter_node'
  autoload :ChannelMergerNode,               'interfaces/channel_merger_node'
  autoload :ChannelSplitterNode,             'interfaces/channel_splitter_node'
  autoload :ConvolverNode,                   'interfaces/convolver_node'
  autoload :DelayNode,                       'interfaces/delay_node'
  autoload :DynamicsCompressorNode,          'interfaces/dynamics_compressor_node'
  autoload :GainNode,                        'interfaces/gain_node'
  autoload :IIRFilterNode,                   'interfaces/iir_filter_node'
  autoload :OscillatorNode,                  'interfaces/oscillator_node'
  autoload :PannerNode,                      'interfaces/panner_node'
  autoload :PeriodicWave,                    'interfaces/periodic_wave'
  autoload :WaveSharperNode,                 'interfaces/wave_sharper_node'
end